package com.example.retail.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.0
 * 2023-11-26T23:55:32.958-05:00
 * Generated source version: 4.0.0
 *
 */
@WebServiceClient(name = "WSDemoService",
                  wsdlLocation = "file:/D:/pocs/soap-demo/src/main/resources/hello-world.wsdl",
                  targetNamespace = "http://retail.tmobile.com/service")
public class WSDemoService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://retail.tmobile.com/service", "WSDemoService");
    public final static QName WSDemoPort = new QName("http://retail.tmobile.com/service", "WSDemoPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/pocs/soap-demo/src/main/resources/hello-world.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WSDemoService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/D:/pocs/soap-demo/src/main/resources/hello-world.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WSDemoService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WSDemoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSDemoService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public WSDemoService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WSDemoService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WSDemoService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns WSDemo
     */
    @WebEndpoint(name = "WSDemoPort")
    public WSDemo getWSDemoPort() {
        return super.getPort(WSDemoPort, WSDemo.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSDemo
     */
    @WebEndpoint(name = "WSDemoPort")
    public WSDemo getWSDemoPort(WebServiceFeature... features) {
        return super.getPort(WSDemoPort, WSDemo.class, features);
    }

}
