package com.example.retail.service;

import com.example.retail.sdo.ObjectFactory;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.0
 * 2023-11-26T23:55:32.872-05:00
 * Generated source version: 4.0.0
 *
 */
@WebService(targetNamespace = "http://retail.tmobile.com/service", name = "WSDemo")
@XmlSeeAlso({ObjectFactory.class})
public interface WSDemo {

    @WebMethod
    @RequestWrapper(localName = "helloWorld", targetNamespace = "http://retail.tmobile.com/sdo", className = "com.tmobile.retail.sdo.HelloWorld")
    @ResponseWrapper(localName = "helloWorldResponse", targetNamespace = "http://retail.tmobile.com/sdo", className = "com.tmobile.retail.sdo.HelloWorldResponse")
    @WebResult(name = "helloWorldReturn", targetNamespace = "http://retail.tmobile.com/sdo")
    public java.lang.String helloWorld(

        @WebParam(name = "name", targetNamespace = "http://retail.tmobile.com/sdo")
        java.lang.String name
    );
}
